import type { MediaItem } from './types.ts'

const steam = (id: number) =>
  `https://cdn.akamai.steamstatic.com/steam/apps/${id}/library_600x900.jpg`
const tmdb = (file: string) => `https://image.tmdb.org/t/p/w500/${file}.jpg`
const tvmaze = (file: string) =>
  `https://static.tvmaze.com/uploads/images/original_untouched/${file}.jpg`
const mal = (file: string) => `https://cdn.myanimelist.net/images/anime/${file}l.jpg`

const games: MediaItem[] = [
  {
    id: 'game-cyberpunk',
    type: 'game',
    title: 'Cyberpunk 2077',
    originalTitle: 'Cyberpunk 2077',
    year: 2020,
    genres: ['Ролевая', 'Фантастика'],
    description:
      'Найт-Сити не спит. Стань наёмником Ви, найди своё место в городе неоновых обещаний и реши, сколько стоит остаться собой.',
    poster: steam(1091500),
    accent: '#eadf59',
    platforms: ['PC', 'PlayStation', 'Xbox'],
  },
  {
    id: 'game-elden-ring',
    type: 'game',
    title: 'Elden Ring',
    originalTitle: 'Elden Ring',
    year: 2022,
    genres: ['Ролевая', 'Фэнтези'],
    description:
      'Огромное Междуземье, потерянные боги и свобода свернуть с любой дороги. Приключение, в котором каждая победа становится твоей собственной историей.',
    poster: steam(1245620),
    accent: '#c5b071',
    platforms: ['PC', 'PlayStation', 'Xbox'],
  },
  {
    id: 'game-hades',
    type: 'game',
    title: 'Hades',
    originalTitle: 'Hades',
    year: 2020,
    genres: ['Экшен', 'Мифология'],
    description:
      'Загрей снова пытается выбраться из царства мёртвых. Олимп помогает, отец мешает, а каждый новый побег раскрывает ещё одну семейную тайну.',
    poster: steam(1145360),
    accent: '#e97862',
    platforms: ['PC', 'PlayStation', 'Xbox', 'Switch'],
  },
  {
    id: 'game-stray',
    type: 'game',
    title: 'Stray',
    originalTitle: 'Stray',
    year: 2022,
    genres: ['Приключения', 'Фантастика'],
    description:
      'Маленький кот в большом городе роботов. Исследуй крыши и переулки, знакомься с необычными жителями и найди дорогу к свету.',
    poster: steam(1332010),
    accent: '#edab69',
    platforms: ['PC', 'PlayStation', 'Xbox', 'Switch'],
  },
  {
    id: 'game-hollow-knight',
    type: 'game',
    title: 'Hollow Knight',
    originalTitle: 'Hollow Knight',
    year: 2017,
    genres: ['Приключения', 'Фэнтези'],
    description:
      'Тихое путешествие в забытое королевство под землёй. За каждым поворотом ждут красивые руины, упрямые противники и немного печали.',
    poster: steam(367520),
    accent: '#a9c7de',
    platforms: ['PC', 'PlayStation', 'Xbox', 'Switch'],
  },
  {
    id: 'game-disco-elysium',
    type: 'game',
    title: 'Disco Elysium',
    originalTitle: 'Disco Elysium: The Final Cut',
    year: 2019,
    genres: ['Ролевая', 'Детектив'],
    description:
      'Детектив без памяти просыпается в городе с долгой историей. Разговаривай с людьми и собственными мыслями: иногда раскрыть себя сложнее, чем преступление.',
    poster: steam(632470),
    accent: '#f09e75',
    platforms: ['PC', 'PlayStation', 'Xbox', 'Switch'],
  },
  {
    id: 'game-rdr2',
    type: 'game',
    title: 'Red Dead Redemption 2',
    originalTitle: 'Red Dead Redemption 2',
    year: 2018,
    genres: ['Приключения', 'Драма'],
    description:
      'Последние дни Дикого Запада глазами Артура Моргана. Дорога, верность и трудный выбор между своей бандой и собственной совестью.',
    poster: steam(1174180),
    accent: '#ed6f61',
    platforms: ['PC', 'PlayStation', 'Xbox'],
  },
  {
    id: 'game-death-stranding',
    type: 'game',
    title: 'Death Stranding',
    originalTitle: 'Death Stranding',
    year: 2019,
    genres: ['Приключения', 'Фантастика'],
    description:
      'Шаг за шагом соединяй разорванный мир. Необычное путешествие о расстояниях между людьми, ответственности и красоте пустых пейзажей.',
    poster: steam(1850570),
    accent: '#98becb',
    platforms: ['PC', 'PlayStation', 'Xbox'],
  },
]

const movies: MediaItem[] = [
  {
    id: 'movie-dune',
    type: 'movie',
    title: 'Дюна: Часть вторая',
    originalTitle: 'Dune: Part Two',
    year: 2024,
    genres: ['Фантастика', 'Приключения'],
    description:
      'Песок помнит всё. Пол Атрейдес присоединяется к фременам и оказывается между любовью, долгом и будущим, которого боится. Монументальное путешествие в самое сердце Арракиса.',
    poster: tmdb('1pdfLvkbY9ohJlCjQH2CZjjYVvJ'),
    accent: '#dba175',
    duration: 166,
  },
  {
    id: 'movie-interstellar',
    type: 'movie',
    title: 'Интерстеллар',
    originalTitle: 'Interstellar',
    year: 2014,
    genres: ['Фантастика', 'Драма'],
    description:
      'Когда Земля перестаёт быть домом, команда исследователей отправляется за пределы знакомой Вселенной. История о времени, надежде и связи, которой не страшны расстояния.',
    poster: tmdb('yQvGrMoipbRoddT0ZR8tPoR7NfX'),
    accent: '#b8cbd4',
    duration: 169,
  },
  {
    id: 'movie-blade-runner',
    type: 'movie',
    title: 'Бегущий по лезвию 2049',
    originalTitle: 'Blade Runner 2049',
    year: 2017,
    genres: ['Фантастика', 'Детектив'],
    description:
      'Офицер Кей находит тайну, способную изменить хрупкий порядок будущего. Дождь, неон и поиски ответа на вопрос, что делает воспоминания настоящими.',
    poster: tmdb('gajva2L0rPYkEWjzgFlBXCAVBE5'),
    accent: '#eba16e',
    duration: 164,
  },
  {
    id: 'movie-everything',
    type: 'movie',
    title: 'Всё везде и сразу',
    originalTitle: 'Everything Everywhere All at Once',
    year: 2022,
    genres: ['Фантастика', 'Комедия'],
    description:
      'Стирка, налоги и бесконечные версии одной жизни. Эвелин предстоит спасти мультивселенную и понять самое важное в своей собственной семье.',
    poster: tmdb('w3LxiVYdWWRvEVdn5RYq6jIqkb1'),
    accent: '#eb8b99',
    duration: 139,
  },
  {
    id: 'movie-spiderverse',
    type: 'movie',
    title: 'Человек-паук: Паутина вселенных',
    originalTitle: 'Spider-Man: Across the Spider-Verse',
    year: 2023,
    genres: ['Анимация', 'Приключения'],
    description:
      'Майлз Моралес попадает в миры других Людей-пауков. Визуально невероятное путешествие о взрослении и праве написать собственную историю.',
    poster: tmdb('8Vt6mWEReuy4Of61Lnj5Xj704m8'),
    accent: '#d991d1',
    duration: 140,
  },
  {
    id: 'movie-oppenheimer',
    type: 'movie',
    title: 'Оппенгеймер',
    originalTitle: 'Oppenheimer',
    year: 2023,
    genres: ['Драма', 'История'],
    description:
      'Портрет учёного, чья работа изменила мир. История амбиций, большой науки и ответственности за последствия собственных открытий.',
    poster: tmdb('ptpr0kGAckfQkJeJIt8st5dglvd'),
    accent: '#efaa68',
    duration: 180,
  },
  {
    id: 'movie-budapest',
    type: 'movie',
    title: 'Отель «Гранд Будапешт»',
    originalTitle: 'The Grand Budapest Hotel',
    year: 2014,
    genres: ['Комедия', 'Приключения'],
    description:
      'Консьерж Густав и юный портье Зеро оказываются в центре невероятного наследственного спора. Симметрия, розовые фасады и большая дружба в маленьком мире.',
    poster: tmdb('eWdyYQreja6JGCzqHWXpWHDrrPo'),
    accent: '#e5a5b6',
    duration: 100,
  },
  {
    id: 'movie-whiplash',
    type: 'movie',
    title: 'Одержимость',
    originalTitle: 'Whiplash',
    year: 2014,
    genres: ['Драма', 'Музыка'],
    description:
      'Молодой барабанщик мечтает о величии, а его преподаватель не признаёт компромиссов. Напряжённая история о границе между страстью и одержимостью.',
    poster: tmdb('7fn624j5lj3xTme2SgiLCeuedmO'),
    accent: '#c9ac78',
    duration: 107,
  },
]

const series: MediaItem[] = [
  {
    id: 'series-severance',
    type: 'series',
    title: 'Разделение',
    originalTitle: 'Severance',
    year: 2022,
    genres: ['Фантастика', 'Триллер'],
    description:
      'В компании Lumon рабочие воспоминания отделены от личных. Идеальный баланс жизни и работы оказывается куда тревожнее, чем звучит. В подборке первые два сезона.',
    poster: tvmaze('548/1371406'),
    accent: '#95b9d1',
    episodes: 19,
    seasons: 2,
  },
  {
    id: 'series-dark',
    type: 'series',
    title: 'Тьма',
    originalTitle: 'Dark',
    year: 2017,
    genres: ['Фантастика', 'Детектив'],
    description:
      'Исчезновение ребёнка в маленьком немецком городе связывает судьбы четырёх семей. В этом лабиринте вопрос «когда» важнее вопроса «где».',
    poster: tvmaze('504/1262352'),
    accent: '#bac38c',
    episodes: 26,
    seasons: 3,
  },
  {
    id: 'series-arcane',
    type: 'series',
    title: 'Аркейн',
    originalTitle: 'Arcane',
    year: 2021,
    genres: ['Анимация', 'Фэнтези'],
    description:
      'Две сестры по разные стороны расколотого города. Живописная история о любви, изобретениях и цене прогресса во вселенной League of Legends.',
    poster: tvmaze('536/1340287'),
    accent: '#aaa2e4',
    episodes: 18,
    seasons: 2,
  },
  {
    id: 'series-mr-robot',
    type: 'series',
    title: 'Мистер Робот',
    originalTitle: 'Mr. Robot',
    year: 2015,
    genres: ['Триллер', 'Драма'],
    description:
      'Днём Эллиот защищает компьютерные сети, ночью ищет справедливость своими методами. Встреча с таинственным хакером меняет его представление о реальности.',
    poster: tvmaze('211/528026'),
    accent: '#ea8c7c',
    episodes: 45,
    seasons: 4,
  },
  {
    id: 'series-breaking-bad',
    type: 'series',
    title: 'Во все тяжкие',
    originalTitle: 'Breaking Bad',
    year: 2008,
    genres: ['Драма', 'Триллер'],
    description:
      'Учитель химии Уолтер Уайт узнаёт о тяжёлой болезни и принимает решение, которое навсегда меняет его семью. История медленного и страшного превращения.',
    poster: tvmaze('501/1253519'),
    accent: '#bed19b',
    episodes: 62,
    seasons: 5,
  },
  {
    id: 'series-chernobyl',
    type: 'series',
    title: 'Чернобыль',
    originalTitle: 'Chernobyl',
    year: 2019,
    genres: ['Драма', 'История'],
    description:
      'Пять эпизодов о катастрофе, цене лжи и людях, которые не могли позволить себе отступить. Художественная история событий весны 1986 года.',
    poster: tvmaze('193/482599'),
    accent: '#a3c4ab',
    episodes: 5,
    seasons: 1,
  },
  {
    id: 'series-queens-gambit',
    type: 'series',
    title: 'Ход королевы',
    originalTitle: "The Queen's Gambit",
    year: 2020,
    genres: ['Драма'],
    description:
      'Бет Хармон открывает для себя шахматы и начинает путь к вершине. За красивыми партиями скрывается непростая борьба с одиночеством и зависимостью.',
    poster: tvmaze('510/1275203'),
    accent: '#d7a27e',
    episodes: 7,
    seasons: 1,
  },
  {
    id: 'series-fleabag',
    type: 'series',
    title: 'Дрянь',
    originalTitle: 'Fleabag',
    year: 2016,
    genres: ['Комедия', 'Драма'],
    description:
      'Ироничная лондонская девушка пытается разобраться с семьёй, близостью и самой собой. Неловко, смешно и неожиданно очень честно.',
    poster: tvmaze('192/482341'),
    accent: '#d09c9b',
    episodes: 12,
    seasons: 2,
  },
]

const anime: MediaItem[] = [
  {
    id: 'anime-frieren',
    type: 'anime',
    title: 'Провожающая в последний путь Фрирен',
    originalTitle: 'Frieren: Beyond Journey’s End',
    year: 2023,
    genres: ['Фэнтези', 'Приключения'],
    description:
      'Большое приключение закончилось. Эльфийская волшебница отправляется в новое путешествие, чтобы наконец понять людей, с которыми спасла мир. В подборке первый сезон.',
    poster: mal('1015/138006'),
    accent: '#accda4',
    episodes: 28,
    seasons: 1,
  },
  {
    id: 'anime-bebop',
    type: 'anime',
    title: 'Ковбой Бибоп',
    originalTitle: 'Cowboy Bebop',
    year: 1998,
    genres: ['Фантастика', 'Приключения'],
    description:
      'Команда охотников за головами путешествует по Солнечной системе под джаз. Космический вестерн о прошлом, которое всегда летит следом.',
    poster: mal('4/19644'),
    accent: '#dab38e',
    episodes: 26,
    seasons: 1,
  },
  {
    id: 'anime-death-note',
    type: 'anime',
    title: 'Тетрадь смерти',
    originalTitle: 'Death Note',
    year: 2006,
    genres: ['Триллер', 'Детектив'],
    description:
      'Школьник находит тетрадь, способную решать чужие судьбы. Его представлению о справедливости бросает вызов загадочный детектив L.',
    poster: mal('9/9453'),
    accent: '#bf9aae',
    episodes: 37,
    seasons: 1,
  },
  {
    id: 'anime-chainsaw',
    type: 'anime',
    title: 'Человек-бензопила',
    originalTitle: 'Chainsaw Man',
    year: 2022,
    genres: ['Экшен', 'Фэнтези'],
    description:
      'Дэндзи мечтает о самой обычной жизни, но заключает необычный договор с демоном. Дикая, яркая и удивительно человечная история. Первый сезон.',
    poster: mal('1806/126216'),
    accent: '#e4a175',
    episodes: 12,
    seasons: 1,
  },
  {
    id: 'anime-fullmetal',
    type: 'anime',
    title: 'Стальной алхимик: Братство',
    originalTitle: 'Fullmetal Alchemist: Brotherhood',
    year: 2009,
    genres: ['Фэнтези', 'Приключения'],
    description:
      'Братья Элрик ищут способ вернуть утраченное после запрещённого эксперимента. Большое путешествие о цене знаний и равнозначном обмене.',
    poster: mal('1223/96541'),
    accent: '#b9b4ca',
    episodes: 64,
    seasons: 1,
  },
  {
    id: 'anime-demon-slayer',
    type: 'anime',
    title: 'Клинок, рассекающий демонов',
    originalTitle: 'Demon Slayer: Kimetsu no Yaiba',
    year: 2019,
    genres: ['Экшен', 'Фэнтези'],
    description:
      'Тандзиро становится охотником на демонов, чтобы спасти сестру. Семейная верность и невероятно красивые сражения. В подборке первый сезон.',
    poster: mal('1286/99889'),
    accent: '#86c4b7',
    episodes: 26,
    seasons: 1,
  },
  {
    id: 'anime-steins-gate',
    type: 'anime',
    title: 'Врата Штейна',
    originalTitle: 'Steins;Gate',
    year: 2011,
    genres: ['Фантастика', 'Триллер'],
    description:
      'Компания друзей случайно находит способ отправлять сообщения в прошлое. Безобидные эксперименты начинают менять настоящее.',
    poster: mal('5/73199'),
    accent: '#c5b69d',
    episodes: 24,
    seasons: 1,
  },
  {
    id: 'anime-mob',
    type: 'anime',
    title: 'Моб Психо 100',
    originalTitle: 'Mob Psycho 100',
    year: 2016,
    genres: ['Экшен', 'Комедия'],
    description:
      'Шигэо обладает огромной сверхъестественной силой, но хочет всего лишь подружиться с одноклассниками. История о том, что делает человека особенным.',
    poster: mal('8/80356'),
    accent: '#92c1dc',
    episodes: 37,
    seasons: 3,
  },
]

export const catalog: MediaItem[] = movies.flatMap((movie, index) => [
  movie,
  games[index],
  series[index],
  anime[index],
])
export const featuredIds = [
  'movie-dune',
  'game-cyberpunk',
  'anime-frieren',
  'series-severance',
  'movie-blade-runner',
]
