// Canonical genres are English display names. Providers normalise through `canonicalGenre`,
// the client localises through `genreLabel`. Unknown genres pass through unchanged.

const SYNONYMS: Record<string, string> = {
  'science-fiction': 'Sci-Fi',
  'science fiction': 'Sci-Fi',
  'sci-fi': 'Sci-Fi',
  scifi: 'Sci-Fi',
  'sci-fi & fantasy': 'Sci-Fi',
  'role-playing': 'RPG',
  'role playing': 'RPG',
  rpg: 'RPG',
  'role-playing game': 'RPG',
  'action rpg': 'Action RPG',
  jrpg: 'JRPG',
  sports: 'Sport',
  sport: 'Sport',
  children: 'Kids',
  kids: 'Kids',
  'reality-tv': 'Reality',
  reality: 'Reality',
  'talk-show': 'Talk Show',
  'game-show': 'Game Show',
  'slice of life': 'Slice of Life',
  historical: 'History',
  history: 'History',
  'massively multiplayer': 'MMO',
  mmo: 'MMO',
  mmorpg: 'MMO',
  'free to play': 'Free to Play',
  'free-to-play': 'Free to Play',
  'point-and-click': 'Point & Click',
  'point & click': 'Point & Click',
  'first-person shooter': 'FPS',
  fps: 'FPS',
  'shoot em up': "Shoot 'Em Up",
  "shoot 'em up": "Shoot 'Em Up",
  soulslike: 'Souls-like',
  'souls-like': 'Souls-like',
  'rogue-like': 'Roguelike',
  roguelike: 'Roguelike',
  'rogue-lite': 'Roguelite',
  roguelite: 'Roguelite',
  'turn-based': 'Turn-Based',
  'turn-based strategy': 'Turn-Based Strategy',
  'turn-based tactics': 'Turn-Based Tactics',
  'hack and slash': 'Hack and Slash',
  "hack 'n' slash": 'Hack and Slash',
  'open world': 'Open World',
  'story rich': 'Story Rich',
  'co-op': 'Co-op',
  coop: 'Co-op',
  'online co-op': 'Co-op',
  'visual novel': 'Visual Novel',
  'card game': 'Card Game',
  'city builder': 'City Builder',
  'city-builder': 'City Builder',
  'psychological horror': 'Psychological Horror',
  'survival horror': 'Survival Horror',
  'early access': 'Early Access',
  'martial arts': 'Martial Arts',
  'super power': 'Super Power',
  'award winning': 'Award Winning',
  'avant garde': 'Avant Garde',
  'boys love': 'Boys Love',
  'girls love': 'Girls Love',
  'mahou shoujo': 'Mahou Shoujo',
  'magical girl': 'Mahou Shoujo',
  'time travel': 'Time Travel',
  'video game': 'Video Game',
  'strategy game': 'Strategy',
  'team sports': 'Sport',
  'combat sports': 'Sport',
  'urban fantasy': 'Urban Fantasy',
  'dark fantasy': 'Dark Fantasy',
  'gag humor': 'Comedy',
  'adult cast': 'Adult Cast',
  'performing arts': 'Performing Arts',
  'organized crime': 'Crime',
  'love polygon': 'Romance',
  'romantic subtext': 'Romance',
  'animation & modeling': 'Animation',
  anime: 'Anime',
  'tv movie': 'TV Movie',
  espionage: 'Espionage',
  'character action game': 'Hack and Slash',
  'spectacle fighter': 'Hack and Slash',
  'open world survival craft': 'Survival',
  'strategy rpg': 'Tactical RPG',
  'film-noir': 'Film Noir',
  cars: 'Racing',
  game: 'Video Game',
  'work life': 'Workplace',
  'shoujo ai': 'Girls Love',
  'shounen ai': 'Boys Love',
  dementia: 'Avant Garde',
  'love status quo': 'Romance',
  'idols (female)': 'Idols',
  'idols (male)': 'Idols',
  'war & politics': 'War',
  'action & adventure': 'Action',
}

const RU: Record<string, string> = {
  Action: 'Экшен',
  'Action RPG': 'Экшен-RPG',
  'Action-Adventure': 'Приключенческий экшен',
  Adventure: 'Приключения',
  Animation: 'Анимация',
  Anime: 'Аниме',
  Arcade: 'Аркада',
  Biography: 'Биография',
  'Card Game': 'Карточная игра',
  Casual: 'Казуальная',
  'City Builder': 'Градостроение',
  Comedy: 'Комедия',
  'Co-op': 'Кооператив',
  Crime: 'Криминал',
  'Dark Fantasy': 'Тёмное фэнтези',
  Detective: 'Детектив',
  Documentary: 'Документальный',
  Drama: 'Драма',
  'Early Access': 'Ранний доступ',
  Ecchi: 'Этти',
  Espionage: 'Шпионский',
  Family: 'Семейный',
  Fantasy: 'Фэнтези',
  Fighting: 'Файтинг',
  Food: 'Кулинария',
  FPS: 'Шутер от первого лица',
  'Free to Play': 'Бесплатная',
  'Game Show': 'Игровое шоу',
  Gore: 'Жестокость',
  'Hack and Slash': 'Слэшер',
  Harem: 'Гарем',
  History: 'История',
  Horror: 'Ужасы',
  Indie: 'Инди',
  Isekai: 'Исекай',
  Iyashikei: 'Иясикэй',
  Josei: 'Дзёсэй',
  JRPG: 'JRPG',
  Kids: 'Детский',
  Legal: 'Юридический',
  'Martial Arts': 'Боевые искусства',
  Mecha: 'Меха',
  Medical: 'Медицина',
  Metroidvania: 'Метроидвания',
  Military: 'Военный',
  MMO: 'MMO',
  Multiplayer: 'Мультиплеер',
  Music: 'Музыка',
  Musical: 'Мюзикл',
  Mystery: 'Детектив',
  Mythology: 'Мифология',
  Nature: 'Природа',
  News: 'Новости',
  'Open World': 'Открытый мир',
  Parody: 'Пародия',
  Platformer: 'Платформер',
  'Point & Click': 'Point & Click',
  Psychological: 'Психологический',
  'Psychological Horror': 'Психологический хоррор',
  Puzzle: 'Головоломка',
  Racing: 'Гонки',
  Reality: 'Реалити-шоу',
  Reincarnation: 'Реинкарнация',
  Roguelike: 'Рогалик',
  Roguelite: 'Роглайт',
  Romance: 'Мелодрама',
  RPG: 'Ролевая',
  Samurai: 'Самураи',
  Sandbox: 'Песочница',
  School: 'Школа',
  'Sci-Fi': 'Фантастика',
  Seinen: 'Сэйнэн',
  "Shoot 'Em Up": 'Shoot ’em up',
  Shooter: 'Шутер',
  Shoujo: 'Сёдзё',
  Shounen: 'Сёнэн',
  Simulation: 'Симулятор',
  'Slice of Life': 'Повседневность',
  'Souls-like': 'Соулслайк',
  Space: 'Космос',
  Sport: 'Спорт',
  Stealth: 'Стелс',
  Strategy: 'Стратегия',
  'Story Rich': 'Сюжетная',
  'Super Power': 'Суперсила',
  Supernatural: 'Сверхъестественное',
  Survival: 'Выживание',
  'Survival Horror': 'Survival horror',
  Suspense: 'Саспенс',
  Tactical: 'Тактика',
  'Talk Show': 'Ток-шоу',
  Thriller: 'Триллер',
  'Time Travel': 'Путешествия во времени',
  Travel: 'Путешествия',
  'Turn-Based': 'Пошаговая',
  'Turn-Based Strategy': 'Пошаговая стратегия',
  'Turn-Based Tactics': 'Пошаговая тактика',
  'TV Movie': 'Телефильм',
  'Urban Fantasy': 'Городское фэнтези',
  Vampire: 'Вампиры',
  'Video Game': 'Видеоигры',
  'Visual Novel': 'Визуальная новелла',
  War: 'Военный',
  Western: 'Вестерн',
  'Award Winning': 'Отмеченное наградами',
  'Avant Garde': 'Авангард',
  'Boys Love': 'Сёнэн-ай',
  'Girls Love': 'Сёдзё-ай',
  'Mahou Shoujo': 'Махо-сёдзё',
  'Adult Cast': 'Взрослые персонажи',
  'Performing Arts': 'Исполнительское искусство',
  Workplace: 'Работа',
  Idols: 'Идолы',
  Gourmet: 'Гурман',
  Sports: 'Спорт',
  'Action Roguelike': 'Экшен-рогалик',
  'Roguelike Deckbuilder': 'Рогалик-колодостроение',
  Deckbuilding: 'Колодостроение',
  'Card Battler': 'Карточные бои',
  'Trading Card Game': 'Коллекционная карточная игра',
  'Board Game': 'Настольная игра',
  'Tower Defense': 'Защита башен',
  Wargame: 'Варгейм',
  'Auto Battler': 'Автобаттлер',
  'Colony Sim': 'Симулятор колонии',
  'Life Sim': 'Симулятор жизни',
  'Farming Sim': 'Фермерский симулятор',
  'Space Sim': 'Космический симулятор',
  'Automobile Sim': 'Автосимулятор',
  'Grand Strategy': 'Глобальная стратегия',
  RTS: 'Стратегия в реальном времени',
  '4X': '4X',
  CRPG: 'CRPG',
  MOBA: 'MOBA',
  'Party-Based RPG': 'Партийная RPG',
  'Tactical RPG': 'Тактическая RPG',
  "Beat 'Em Up": 'Beat ’em up',
  '2D Fighter': '2D-файтинг',
  '3D Fighter': '3D-файтинг',
  'Third-Person Shooter': 'Шутер от третьего лица',
  'Hero Shooter': 'Геройский шутер',
  'Looter Shooter': 'Лутер-шутер',
  'Extraction Shooter': 'Экстракшен-шутер',
  'Arena Shooter': 'Арена-шутер',
  'Boomer Shooter': 'Олдскульный шутер',
  'Twin Stick Shooter': 'Твин-стик шутер',
  'Top-Down Shooter': 'Шутер с видом сверху',
  'Bullet Hell': 'Буллет-хелл',
  'Battle Royale': 'Королевская битва',
  '2D Platformer': '2D-платформер',
  '3D Platformer': '3D-платформер',
  'Precision Platformer': 'Хардкорный платформер',
  'Puzzle Platformer': 'Платформер-головоломка',
  'Interactive Fiction': 'Интерактивная литература',
  'Dating Sim': 'Симулятор свиданий',
  'Hidden Object': 'Поиск предметов',
  'Walking Simulator': 'Симулятор ходьбы',
  'Immersive Sim': 'Иммерсив-сим',
  'Dungeon Crawler': 'Данжен-кроулер',
  Rhythm: 'Ритм-игра',
  'Party Game': 'Игра для компании',
  Cyberpunk: 'Киберпанк',
  'Post-Apocalyptic': 'Постапокалипсис',
  Management: 'Менеджмент',
  Crafting: 'Крафтинг',
  'Base Building': 'Строительство базы',
  Building: 'Строительство',
  Automation: 'Автоматизация',
  Zombies: 'Зомби',
  Superhero: 'Супергерои',
  Cozy: 'Уютная',
  Short: 'Короткометражный',
  'Film Noir': 'Нуар',
  DIY: 'Своими руками',
  Demons: 'Демоны',
  Magic: 'Магия',
  Police: 'Полиция',
  Anthropomorphic: 'Антропоморфизм',
  CGDCT: 'Милые девушки',
  Childcare: 'Воспитание детей',
  Crossdressing: 'Переодевание',
  Delinquents: 'Хулиганы',
  Educational: 'Образовательное',
  'High Stakes Game': 'Игры с высокими ставками',
  'Otaku Culture': 'Культура отаку',
  Pets: 'Питомцы',
  Showbiz: 'Шоу-бизнес',
  'Visual Arts': 'Изобразительное искусство',
  Villainess: 'Злодейка',
  Soap: 'Мыльная опера',
}

function titleCase(value: string) {
  return value
    .split(/(\s|-)/)
    .map((part) => (/^[a-z]/.test(part) ? part[0].toUpperCase() + part.slice(1) : part))
    .join('')
}

/** Normalises a provider genre/tag (English) to the canonical English name. */
export function canonicalGenre(raw: string): string | null {
  const value = raw.trim().replace(/\s+/g, ' ')
  if (!value || value.length > 40) return null
  const key = value.toLowerCase()
  if (SYNONYMS[key]) return SYNONYMS[key]
  const known = Object.keys(RU).find((name) => name.toLowerCase() === key)
  return known ?? titleCase(value)
}

export function canonicalGenres(values: readonly string[], limit = 5): string[] {
  const result: string[] = []
  for (const value of values) {
    const genre = canonicalGenre(value)
    if (genre && !result.includes(genre)) result.push(genre)
    if (result.length >= limit) break
  }
  return result
}

export function genreLabel(genre: string, locale: 'ru' | 'en'): string {
  return locale === 'ru' ? (RU[genre] ?? genre) : genre
}
